export const clue_data = [
  {

    id: 'xM5hDKobR5JzcsspWze2oAOTjUyoQOadPiE5c',
    question_no: '1',
    group_name: 'a',
    code: 'A1DEFG',
    clue: "Desi londo ka kamra",
    clue_image: "",
    next_code: 'C2XYZE',
  },
  {
    id: '11PSZUCEX5HVLNcfxeNTpfdDX3snUxS2iHR5c',
    question_no: '2',
    clue: 'I was a PM and born on 2nd October 1904, find me!',
    clue_image: "",
    group_name: 'a',
    code: 'C2XYZE',
    next_code: 'E3UVWX',
  },
  {
    id: '2tfPTAIGxr77NU8eOWfSq7FbEZZ8vpqGFavnk',
    question_no: '3',
    clue: '',
    clue_image: "/dental.jpg",
    group_name: 'a',
    code: 'E3UVWX',
    next_code: 'G4EFGY',
  },
  {
    id: 'tDdHYlfkTdZQIsLSEKfXWXiO6w0aGQtv5Hp8I',
    question_no: '4',
    clue: '-... .-.. ..- .',
    clue_image: "",
    group_name: 'a',
    code: 'G4EFGY',
    next_code: 'U5ABCL',
  },
  {
    id: 'Ihx6ujplKXi9k93jSLwv20Nvn42brsN4n6R0M',
    question_no: '1',
    clue: '"2" places where are laid, find the "0" notice board where "3" ragging is forbidden.',
    clue_image: "",
    group_name: 'b',
    code: 'A1XYZE',
    next_code: 'C2ABCX',
  },
  {
    id: 'tDS4NYa4XxRxbAAFUcSfVMWtZbZLmt9TRytDc',
    question_no: '2',
    clue: '',
    clue_image: "/319.jpg",
    group_name: 'b',
    code: 'C2ABCX',
    next_code: 'E3XYZH',
  },
  {
    id: 'jSu1n0g7CQR8fYdpAZO8jWB0KCODJ57KAm32J',
    question_no: '3',
    clue: '',
    clue_image: "/workshop.jpg",
    group_name: 'b',
    code: 'E3XYZH',
    next_code: 'G4LMNY',
  },
  {
    id: 'C3zxg7OLG0m75siTj4aNqisXPmfCatTRvz7jK',
    question_no: '4',
    clue: '-... .-.. ..- .',
    clue_image: "",
    group_name: 'b',
    code: 'G4EFGY',
    next_code: 'U5ABCL',
  },
  {
    id: 'kjFFfvGsvMZ3oti3jfLgKIphnQLTqWWkLnTx3',
    question_no: '1',
    clue: 'Malam patti karlo guys, konsa ye room.',
    clue_image: "",
    group_name: 'c',
    code: 'A1HIJS',
    next_code: 'C2DEFZ',
  },
  {
    id: 'Fa7jz5nuijUMHl5fZZzNLZuwY9MVNi8cchOZz',
    question_no: '2',
    clue: 'Albert Einstein was good at Physics',
    clue_image: "",
    group_name: 'c',
    code: 'C2DEFZ',
    next_code: 'E3LMNH',
  },
  {
    id: 'lgSDyHUZm4RyWMGGPvjFuuRTEhbnPYxuXVA3t',
    question_no: '3',
    clue: '',
    clue_image: "/door.jpg",
    group_name: 'c',
    code: 'E3LMNH',
    next_code: 'G4XYZJ',
  },
  {
    id: 'jN6jdu4LZfvFKR0So66G74sJ82G2fuOP1MQz7',
    question_no: '4',
    clue: '-...   .-..  ..-   .    in canteen',
    clue_image: "",
    group_name: 'c',
    code: 'G4EFGY',
    next_code: 'U5ABCL',
  },
  {
    id: '7aFZZLVAIYo6PH9YWDYcqTT0FFxhcdqlPjkKd',
    question_no: '5',
    clue: 'End is where you start',
    clue_image: "",
    group_name: 'abc',
    code: 'U5ABCL',
    next_code: 'Z6ACEZ',
  },
  {
    id: 'jGnoEipvyJcMjoZ1TTbYazYlky2gDwLCeE7iR',
    question_no: '6',
    clue: 'All levels are cleared',
    clue_image: "/passed.webp",
    group_name: 'abc',
    code: 'Z6ACEZ',
    next_code: 'NaN',
  },
];

export const team_data = {
  ALPHA: "a",
  BETA: "b",
  GAMMA: "c",
  ROGER: "a",
  LUFFY: "b",
  ZORO: "c",
  SANJI: "a",
  NAMI: "b",
  USOPP: "c",
  CHOPPER: "a",
  FRANKY: "b",
  BROOK: "c",
  ROBIN: "a",
  JINBEI: "b",
  LAW: "c",
};
