export const clue_data = [
  {
    id: 'xM5hDKobR5JzcsspWze2oAOTjUyoQOadPiE5c',
    question_no: '1',
    group_name: 'a',
    code: '2905',
    clue: "Some of the world's most famous paintings are housed in this museum.",
    next_code: '2906',
  },
  {
    id: '11PSZUCEX5HVLNcfxeNTpfdDX3snUxS2iHR5c',
    question_no: '2',
    clue: 'This is the largest museum in the world.',
    group_name: 'a',
    code: '2906',
    next_code: '2907',
  },
  {
    id: '2tfPTAIGxr77NU8eOWfSq7FbEZZ8vpqGFavnk',
    question_no: '3',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'a',
    code: '2907',
    next_code: '2908',
  },
  {
    id: 'tDdHYlfkTdZQIsLSEKfXWXiO6w0aGQtv5Hp8I',
    question_no: '4',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'a',
    code: '2908',
    next_code: '2909',
  },
  {
    id: 'Ihx6ujplKXi9k93jSLwv20Nvn42brsN4n6R0M',
    question_no: '1',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'b',
    code: '2910',
    next_code: '2911',
  },
  {
    id: 'tDS4NYa4XxRxbAAFUcSfVMWtZbZLmt9TRytDc',
    question_no: '2',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'b',
    code: '2911',
    next_code: '2912',
  },
  {
    id: 'jSu1n0g7CQR8fYdpAZO8jWB0KCODJ57KAm32J',
    question_no: '3',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'b',
    code: '2912',
    next_code: '2913',
  },
  {
    id: 'C3zxg7OLG0m75siTj4aNqisXPmfCatTRvz7jK',
    question_no: '4',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'b',
    code: '2913',
    next_code: '2909',
  },
  {
    id: 'kjFFfvGsvMZ3oti3jfLgKIphnQLTqWWkLnTx3',
    question_no: '1',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'c',
    code: '2915',
    next_code: '2916',
  },
  {
    id: 'Fa7jz5nuijUMHl5fZZzNLZuwY9MVNi8cchOZz',
    question_no: '2',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'c',
    code: '2916',
    next_code: '2917',
  },
  {
    id: 'lgSDyHUZm4RyWMGGPvjFuuRTEhbnPYxuXVA3t',
    question_no: '3',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'c',
    code: '2917',
    next_code: '2918',
  },
  {
    id: 'jN6jdu4LZfvFKR0So66G74sJ82G2fuOP1MQz7',
    question_no: '4',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'c',
    code: '2918',
    next_code: '2909',
  },
  {
    id: '7aFZZLVAIYo6PH9YWDYcqTT0FFxhcdqlPjkKd',
    question_no: '5',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'abc',
    code: '2909',
    next_code: '2921',
  },
  {
    id: 'jGnoEipvyJcMjoZ1TTbYazYlky2gDwLCeE7iR',
    question_no: '6',
    clue: 'All levels are cleared',
    group_name: 'abc',
    code: '2921',
    next_code: 'NaN',
  },
];

export const team_data = {
  alpha: 'a',
  beta: 'b',
  gamma: 'c',
  roger: 'a',
  luffy: 'b',
  zoro: 'c',
  sanji: 'a',
  nami: 'b',
  usopp: 'c',
  chopper: 'a',
  franky: 'b',
  brook: 'c',
};
