export const clue_data = [
  {
    id: 'xM5hDKobR5JzcsspWze2oAOTjUyoQOadPiE5c',
    clue_no: '01',
    level: '1',
    group_name: 'a',
    code: '2905',
    clue: "Some of the world's most famous paintings are housed in this museum.",
    next_code: '2908',
  },
  {
    id: '11PSZUCEX5HVLNcfxeNTpfdDX3snUxS2iHR5c',
    clue_no: '02',
    clue: 'This is the largest museum in the world.',
    group_name: 'b',
    code: '2906',
    next_code: '2909',
    level: '1',
  },
  {
    id: '2tfPTAIGxr77NU8eOWfSq7FbEZZ8vpqGFavnk',
    clue_no: '03',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'c',
    code: '2907',
    next_code: '2910',
    level: '1',
  },
  {
    id: 'tDdHYlfkTdZQIsLSEKfXWXiO6w0aGQtv5Hp8I',
    clue_no: '04',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'a',
    code: '2908',
    next_code: '2911',
  },
  {
    id: 'Ihx6ujplKXi9k93jSLwv20Nvn42brsN4n6R0M',
    clue_no: '05',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'b',
    code: '2909',
    next_code: '2912',
  },
  {
    id: 'tDS4NYa4XxRxbAAFUcSfVMWtZbZLmt9TRytDc',
    clue_no: '06',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'c',
    code: '2910',
    next_code: '2913',
  },
  {
    id: 'xM5hDKobR5JzcsspWze2oAOTjUyoQOadPiE5c',
    clue_no: '07',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'abc',
    code: '2911',
    next_code: '2912',
  },
  {
    id: '11PSZUCEX5HVLNcfxeNTpfdDX3snUxS2iHR5c',
    clue_no: '08',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'abc',
    code: '2912',
    next_code: '2913',
  },
  {
    id: '2tfPTAIGxr77NU8eOWfSq7FbEZZ8vpqGFavnk',
    clue_no: '09',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'abc',
    code: '2913',
    next_code: '2914',
  },
  {
    id: 'tDdHYlfkTdZQIsLSEKfXWXiO6w0aGQtv5Hp8I',
    clue_no: '10',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'abc',
    code: '2914',
    next_code: '2915',
  },
  {
    id: 'Ihx6ujplKXi9k93jSLwv20Nvn42brsN4n6R0M',
    clue_no: '11',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'abc',
    code: '2915',
    next_code: '2916',
  },
  {
    id: 'tDS4NYa4XxRxbAAFUcSfVMWtZbZLmt9TRytDc',
    clue_no: '12',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'abc',
    code: '2916',
    next_code: '2917',
  },
  {
    id: 'xM5hDKobR5JzcsspWze2oAOTjUyoQOadPiE5c',
    clue_no: '13',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'abc',
    code: '2917',
    next_code: '2918',
  },
  {
    id: '11PSZUCEX5HVLNcfxeNTpfdDX3snUxS2iHR5c',
    clue_no: '14',
    clue: 'This museum is home to the Mona Lisa.',
    group_name: 'abc',
    code: '2918',
    next_code: '2919',
  },
];

export const team_data = {
  alpha: 'a',
  beta: 'b',
  gamma: 'c',
  roger: 'a',
  luffy: 'b',
  zoro: 'c',
  sanji: 'a',
  nami: 'b',
  usopp: 'c',
  chopper: 'a',
  franky: 'b',
  brook: 'c',
};
